[lutris]
library_ignores = 
migration_version = 12
selected_category = category:all
width = 1911
height = 2034
maximized = False
show_advanced_options = True
window_x = 1923
window_y = 70
filter_installed = False
show_hidden_games = true

[services]
lutris = True
gog = True
humblebundle = True
steam = True
egs = True
origin = True
ubisoft = True

