# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

general {
    lock_cmd = pidof hyprlock || hyprlock           # Avoid starting multiple hyprlock instances.
    # before_sleep_cmd = loginctl lock-session      # Lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on      # Avoid having to press a key twice to turn on the display.
}

## Lock the current session.
#listener {
#    timeout = 300                                  # 5 min
#    on-timeout = loginctl lock-session             # Lock the screen when timeout has passed.
#}

# Turn the screen off.
listener {
    timeout = 900                                   # 15 min
    on-timeout = hyprctl dispatch dpms off          # Turn the screen off when timeout has passed
    on-resume  = hyprctl dispatch dpms on           # Turn the screen on  when activity is detected after timeout has fired.
}

# Suspend the PC.
listener {
    timeout = 1800                                  # 30 min
    on-timeout = systemctl suspend                  # Suspend the PC.
}
