# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

# All colors needs to be expressed in RRGGBB[AA] format.

timeout = 1000
max = 100
width = 400
height = 35
border_offset = 0
border_size = 2
bar_padding = 4
anchor = center
margin = 0
border_color = 369ecfff
background_color = 00000088
bar_color = 3bb4e8f0
#overflow_mode = wrap
#overflow_bar_color = ff000000
#overflow_background_color = 000000ff
#overflow_border_color = ffffffff
output_mode = all
orientation = horizontal
