# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

# #########################
# ## Hyprland animations ##
# #########################

# See https://wiki.hyprland.org/Configuring/Variables/ for more

animations {
    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    enabled = yes

    # Note:  Beziers    --> NAME, X0, Y0,    X1,    Y1
    #        Animations --> NAME, ON, SPEED, CURVE, STYLE

    # ########################
    # ## Default animations ##
    # ########################

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows,     1, 7,  myBezier
    animation = windowsOut,  1, 7,  default, popin 80%
    animation = border,      1, 10, default
    animation = borderangle, 1, 8,  default
    animation = fade,        1, 7,  default
    animation = workspaces,  1, 6,  default

    # #####################
    # ## Fast animations ##
    # #####################

    # bezier = linear,        0,    0,    1,    1
    # bezier = md3_standard,  0.2,  0,    0,    1
    # bezier = md3_decel,     0.05, 0.7,  0.1,  1
    # bezier = md3_accel,     0.3,  0,    0.8,  0.15
    # bezier = overshot,      0.05, 0.9,  0.1,  1.1
    # bezier = crazyshot,     0.1,  1.5,  0.76, 0.92
    # bezier = hyprnostretch, 0.05, 0.9,  0.1,  1.0
    # bezier = fluent_decel,  0.1,  1,    0,    1
    # bezier = easeInOutCirc, 0.85, 0,    0.15, 1
    # bezier = easeOutCirc,   0,    0.55, 0.45, 1
    # bezier = easeOutExpo,   0.16, 1,    0.3,  1

    # animation = windows,          1, 3,   md3_decel,   popin 60%
    # animation = border,           1, 10,  default
    # animation = fade,             1, 2.5, md3_decel
    # animation = workspaces,       1, 3.5, easeOutExpo, slide
    # animation = specialWorkspace, 1, 3,   md3_decel,   slidevert

    # ##########################
    # ## Very Fast animations ##
    # ##########################

    # bezier = workspace,  0.17, 1.17, 0.3,  1
    # bezier = windowin,   0.15, 1.15, 0.95, 1
    # bezier = windowmove, 0.7,  0.7,  0.1,  1.05

    # animation = windows,          1, 3,   default,    popin
    # animation = windowsIn,        1, 3.2, windowin,   popin 95%
    # animation = windowsOut,       1, 4,   default,    popin 96%
    # animation = windowsMove,      1, 4,   windowmove, slide
    # animation = workspaces,       1, 5,   workspace,  slidefadevert 7%
    # animation = specialWorkspace, 1, 5,   workspace,  slidefadevert 10%
    # first_launch_animation = true

    # #####################
    # ## High animations ##
    # #####################

    # bezier = wind,   0.05, 0.9,  0.1, 1.05
    # bezier = winIn,  0.1,  1.1,  0.1, 1.1
    # bezier = winOut, 0.3,  -0.3, 0,   1
    # bezier = liner,  1,    1,    1,   1

    # animation = windows,     1, 6,  wind,   slide
    # animation = windowsIn,   1, 6,  winIn,  slide
    # animation = windowsOut,  1, 5,  winOut, slide
    # animation = windowsMove, 1, 5,  wind,   slide
    # animation = border,      1, 1,  liner
    # animation = borderangle, 1, 30, liner,  loop
    # animation = fade,        1, 10, default
    # animation = workspaces,  1, 5,  wind

    # #######################
    # ## Moving animations ##
    # #######################

    # bezier = overshot,  0.05, 0.9, 0.1,  1.05
    # bezier = smoothOut, 0.5,  0,   0.99, 0.99
    # bezier = smoothIn,  0.5, -0.5, 0.68, 1.5

    # animation = windows,     1, 5, overshot, slide
    # animation = windowsOut,  1, 3, smoothOut
    # animation = windowsIn,   1, 3, smoothOut
    # animation = windowsMove, 1, 4, smoothIn, slide
    # animation = border,      1, 5, default
    # animation = fade,        1, 5, smoothIn
    # animation = fadeDim,     1, 5, smoothIn
    # animation = workspaces,  1, 6, default
}