# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

# ########################
# ## Hyprland autostart ##
# ########################

# Launch some demons and other system related tools.
exec-once = systemctl --user import-environment LANG LANGUAGE LC_* _XKB_CHARSET XDG_SESSION_COOKIE CLUTTER_BACKEND DESKTOP_SESSION DISPLAY ELM_SCALE GDK_SCALE GDK_DPI_SCALE GDK_BACKEND GTK_USE_PORTAL OZONE_PLATFORM QT_AUTO_SCREEN_SCALE_FACTOR QT_ENABLE_HIGHDPI_SCALING QT_QPA_PLATFORMTHEME QT_QPA_PLATFORM QT_SCALE_FACTOR QT_WAYLAND_DISABLE_WINDOWDECORATION QT_XFT SDL_VIDEODRIVER WAYLAND_DISPLAY XCURSOR_THEME XCURSOR_SIZE XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP XDG_BACKEND
exec-once = dbus-update-activation-environment --systemd --all
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = /usr/bin/xsettingsd --config=~/.config/xsettingsd/xsettingsd.conf
exec-once = hyprctl setcursor Breeze_Light 30
exec-once = hypridle
exec-once = hyprpaper
exec-once = /usr/bin/pypr
exec-once = ~/.config/hypr/scripts/gsettings.sh
# exec-once = ~/.config/hypr/scripts/hyprdesktop.sh
# exec-once = dbus-update-activation-environment --systemd LANG LANGUAGE LC_* _XKB_CHARSET XDG_SESSION_COOKIE CLUTTER_BACKEND DESKTOP_SESSION DISPLAY ELM_SCALE GDK_SCALE GDK_DPI_SCALE GDK_BACKEND GTK_USE_PORTAL OZONE_PLATFORM QT_AUTO_SCREEN_SCALE_FACTOR QT_ENABLE_HIGHDPI_SCALING QT_QPA_PLATFORMTHEME QT_QPA_PLATFORM QT_SCALE_FACTOR QT_WAYLAND_DISABLE_WINDOWDECORATION QT_XFT SDL_VIDEODRIVER WAYLAND_DISPLAY XCURSOR_THEME XCURSOR_SIZE XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP XDG_BACKEND


# Wipe the clipboard at each login.
exec-once = cliphist wipe

# Activate the clipboard for any copied texts or images.
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Launch the following application/scripts at start.
exec-once = ~/.config/hypr/scripts/volume_osd.sh
exec-once = mako
exec-once = waybar
exec-once = ~/.config/hypr/scripts/gkraken.sh
exec-once = ~/.config/hypr/scripts/mailspring.sh