# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

# ##########################
# ## Hyprland decorations ##
# ##########################

# See https://wiki.hyprland.org/Configuring/Variables/ for more

decoration {
    rounding = 16

    # Blur
    blur {
        enabled = true
        size = 3
        passes = 1
    }

    # Shadow
    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}