# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

# ######################
# ## Hyprland devices ##
# ######################

# See https://wiki.hyprland.org/Configuring/Variables/ for more

device {
    # See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

    name = epic-mouse-v1
    sensitivity = -0.5
}