# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

# ######################################
# ## Hyprland environmental variables ##
# ######################################

# Set 'Hyprland' as the window manager.
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

# Note: Smplayer will not play any video if 'env = QT_QPA_PLATFORM,wayland' is setted.
#       No matter the value ('wayland', 'xcb' or 'wayland;xcb').

# Set 'Wayland' as display manager.
env = XDG_SESSION_TYPE,wayland
env = GDK_BACKEND,wayland
env = CLUTTER_BACKEND,wayland
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = OZONE_PLATFORM,wayland
# env = QT_QPA_PLATFORM,wayland

# Set the UI scale factor
env = QT_SCALE_FACTOR,1.0
env = ELM_SCALE,1.0
env = GDK_SCALE,1.0
env = GDK_DPI_SCALE,1.0

# Set the GTK theme
# env = GTK_THEME,breeze-dark

# Set Qt related variables.
env = GTK_USE_PORTAL,1
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,0
env = QT_ENABLE_HIGHDPI_SCALING,0
# env = QT_FONT_DPI,144

# Set the fallback mouse cursor size and looks.
env = XCURSOR_THEME,Breeze_Light
env = XCURSOR_SIZE,30

# Set the mouse cursor size and looks, the Hyprland way.
env = HYPRCURSOR_THEME,Breeze_Light
env = HYPRCURSOR_SIZE,30

# Note: This is happening to me on YouTube and any video/audio player I tried under Hyprland (smplayer, vlc,...).
#       When they go fullscreen the mouse disappears (standard behaviour) and never reappears again (not a standard behavior).
#       No matter how much you move the mouse or if you have leaved the fullscreen mode (for example with the Escape key),
#       the mouse will still not be visible inside the player window (You will need to restart the player).
#
#       I have a RADEON GPU, I don't know if this is related or not.
#
# The following line resolves the issue.
env = WLR_NO_HARDWARE_CURSORS,1