# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

# ######################
# ## Hyprland general ##
# ######################

# See https://wiki.hyprland.org/Configuring/Variables/ for more

general {
    layout = dwindle

    # Gaps
    gaps_in = 5
    gaps_out = 10

    # Borders
    border_size = 4
    col.active_border = rgba(ff658eee) rgba(f05466ee) 45deg
    col.inactive_border = rgba(595959aa)

    # Cursor
    cursor_inactive_timeout = 900
    no_cursor_warps = true
    no_focus_fallback = true

    # Resize
    resize_on_border = false
    hover_icon_on_border = false

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}