# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

# ####################
# ## Hyprland input ##
# ####################

# See https://wiki.hyprland.org/Configuring/Variables/ for more

input {
    kb_layout = us
    kb_variant =
    kb_model = pc104
    kb_options = caps:none
    kb_rules =
    numlock_by_default = false
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.
}