# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

# ############################
# ## Hyprland miscellaneous ##
# ############################

# See https://wiki.hyprland.org/Configuring/Variables/ for more

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    # Set to 0 or 1 to disable the anime mascot wallpapers
    force_default_wallpaper = 0

    # Enable if you use personalized wallpapers
    disable_hyprland_logo = true

    # It will lower the amount of sent frames when nothing is happening on-screen
    vfr = true
}