# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

# #######################
# ## Hyprland monitors ##
# #######################

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=DP-1,3840x2160,auto,1.5
monitor=DP-1,highres,auto,1.5