format = """
$username\
$hostname\
$directory\
$git_branch\
$shell\
$cmd_duration\
$fill\
$time\
$line_break\
$character"""

[username]
style_user = 'green bold'
style_root = 'red bold'
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'on [$hostname]($style) '
trim_at = "."
style = 'bold purple'
disabled = false

[fill]
symbol = ' '

[shell]
fish_indicator = 'Fish  '
bash_indicator = 'Bash  '
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
format = "shell [$indicator]($style) "
style = 'bold purple'
disabled = false

# configure directory
[directory]
read_only = " "
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
truncation_symbol = "…/"
style = "bold italic blue"

[cmd_duration]
format = '🕙 [$duration]($style) '
min_time = 1
show_milliseconds = false
style = "bold italic red"
disabled = false

[time]
disabled = false
format = '[$time]($style) '
time_format = '%T'

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = '[➜](bold green)'    # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[✗](bold red)'
#  

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

#[directory]
#read_only = " "

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[haskell]
symbol = "λ "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = "🐍 "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[nodejs]
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
