# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#5b6268"
blue = "#f05466"
cyan = "#46d9ff"
green = "#2cb5b3"
magenta = "#b970cf"
red = "#f05466"
white = "#968e80"
yellow = "#3bb4e8"

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[colors.normal]
black = "#1c1f24"
blue = "#5b6268"
cyan = "#5699af"
green = "#2bb1af"
magenta = "#c678dd"
red = "#f05466"
white = "#202328"
yellow = "#369ecf"

[colors.primary]
background = "#26292e"
foreground = "#bbc2cf"

[colors.selection]
background = "#ff658e"
foreground = "#26292e"
text = "CellForeground"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[cursor]
unfocused_hollow = false
blink_interval = 500
blink_timeout = 0

[cursor.style]
shape = "Beam"
blinking = "always"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[scrolling]
history = 100000
multiplier = 3

[shell]
program = "/bin/fish"

[window]
dynamic_padding = false
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 88
lines = 24

[window.padding]
x = 6
y = 6
